//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SavedBot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SavedBot.Localization.BotStrings", typeof(BotStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved your file!.
        /// </summary>
        internal static string AddFileSaved {
            get {
                return ResourceManager.GetString("AddFileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now enter the name of the message you want to save.
        /// </summary>
        internal static string AddName {
            get {
                return ResourceManager.GetString("AddName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great, now send the message that you want to save. It can be anything: from text, photo or GIF to location or a contact.
        /// </summary>
        internal static string AddSend {
            get {
                return ResourceManager.GetString("AddSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved your text!.
        /// </summary>
        internal static string AddTextSaved {
            get {
                return ResourceManager.GetString("AddTextSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must activate the bot before using it. Just type  in pm /start to @.
        /// </summary>
        internal static string ErrorBotNotStarted {
            get {
                return ResourceManager.GetString("ErrorBotNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot recognise what you&apos;re trying to say to me. Maybe try one of the commands from /help list?.
        /// </summary>
        internal static string ErrorCommandSeqBroken {
            get {
                return ResourceManager.GetString("ErrorCommandSeqBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You got me, I don&apos;t support this kind of messages yet :(.
        /// </summary>
        internal static string ErrorNotImplemented {
            get {
                return ResourceManager.GetString("ErrorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command.
        /// </summary>
        internal static string ErrorUnknownCommand {
            get {
                return ResourceManager.GetString("ErrorUnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pass a name to /find command.
        /// </summary>
        internal static string FindNoName {
            get {
                return ResourceManager.GetString("FindNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the list of my commands:.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /start;/help;/add {name};/find {name}.
        /// </summary>
        internal static string HelpCommands {
            get {
                return ResourceManager.GetString("HelpCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /add;Remove (Not available);Settings (Not available).
        /// </summary>
        internal static string MenuButtons {
            get {
                return ResourceManager.GetString("MenuButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a command from menu.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
